In [2]:
# import the relevant libraries
import numpy as np

### declaring scalers, vectors, matrices, tensors

In [3]:
# scalars ( is aloso a tensor)
s = 5 
s

5

In [ ]:
# there are two ways to introduce a vector

In [59]:
# vectors 1 ( is also a tensor)
# introducing a one dimensional vector which does not specify its rows or columns
v = np.array([5, -2, 4])
v

array([ 5, -2,  4])

In [60]:
# vectors 2
# introducing a one dimensional vector in the form of a matrix which specifies its rows or columns
v = np.array([[5, -2, 4]])
v

array([[ 5, -2,  4]])

In [62]:
# or
v = np.array([[5], [-2], [4]])
v

array([[ 5],
       [-2],
       [ 4]])

In [5]:
# matrix   ( is aloso a tensor)
m = np.array([[5,12,6], [-3, 0, 14]])
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [6]:
# tensor 
t = np.array ([[[5,12,6],[-3,0,14]],[[2,2,2], [3,3,3]]])
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 2,  2,  2],
        [ 3,  3,  3]]])

In [7]:
m1 = np.array([[5,12,6], [-3, 0, 14]])
m2 = np.array([[2,2,2], [3, 3, 3]])
t = np.array([m1,m2])
t
# as you see tesors are very hard to manually create, because of those confusing brackets, usually we will load, 
# transfer, and preprocess the data to get tensors, and we do not create it manually, but it's good to know how to do so.

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 2,  2,  2],
        [ 3,  3,  3]]])

### data types

In [8]:
type(s)

int

In [9]:
type(v) # 1-dimensional array
# ndarray stands for n-dimensional array

numpy.ndarray

In [10]:
type(m) # 2-dimensional array

numpy.ndarray

In [11]:
# if we want s to be consistent with the orthers
s_array = np.array(5)
s_array

array(5)

In [12]:
type(s_array)

numpy.ndarray

In [13]:
type(t)

numpy.ndarray

### data shapes : returns the shape (dimensions) of a variable

In [15]:
s_array.shape

()

In [16]:
m.shape

(2, 3)

In [17]:
v.shape # it is a column vector

(3,)

In [18]:
# if you want to reshape a column vector to a row vector
v_row_shape = v.reshape(1,3)
v_row_shape  # so for row shape use two [[]] but for column vector one [][][]

array([[ 5, -2,  4]])

In [19]:
# or for row shape
v_row_shape = np.array([[5, -2, 4]])
v_row_shape

array([[ 5, -2,  4]])

In [20]:
# but for column vector one [][][]
v_column_shape = np.array([[5],[-2],[4]])
v_column_shape

array([[ 5],
       [-2],
       [ 4]])

In [21]:
# or we can use reshape
v_column_shape = v_row_shape.reshape(3,1)
v_column_shape

array([[ 5],
       [-2],
       [ 4]])

In [22]:
v_column_shape.shape

(3, 1)

In [23]:
v_row_shape.shape

(1, 3)

In [24]:
t.shape # last number (n) = # of columns , second last number (m) = # of rows, third last number (k) = number of metrices

(2, 2, 3)

### addition and substractions ( need to have the same dimensions)

In [25]:
m1 = np.array([[5,12,6], [-3, 0, 14]])
m2 = np.array([[2,2,2], [3, 3, 3]])
m_add = m1 + m2
m_add

array([[ 7, 14,  8],
       [ 0,  3, 17]])

In [26]:
m_substaction = m1 - m2
m_substaction

array([[ 3, 10,  4],
       [-6, -3, 11]])

In [35]:
# to add or substract matrices and vectors they nee to have the same dimensions, but
# there is one exception: we can add a scaler to a matrix or vector
s = 1
s + m1 

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [36]:
# or scaler can be expressed in the form of a list
s_array = [1]
s + m1


array([[ 6, 13,  7],
       [-2,  1, 15]])

In [37]:
# or 
s = (1)
s + m1

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [44]:
# or
m1 + np.array([5])

array([[10, 17, 11],
       [ 2,  5, 19]])

### transpose of a matrix

In [48]:
# for vectors: transposing chnages a row vector to a column vector and vice versa
v = np.array([[1,2,3]])
v


array([[1, 2, 3]])

In [57]:
# if we do not use [[]], and use [] two declare our vector, it is a 1 dimentional vector and it
# does not have a row or columns shape because we didnot introduce it in the form of a matrix. so 
# transposing does not make any change
w = np.array([1,2,3])
w

array([1, 2, 3])

In [58]:
w.T

array([1, 2, 3])

In [49]:
v_t = np.transpose(v)
v_t

array([[1],
       [2],
       [3]])

In [53]:
# other way using .T
v_t = v.T
v_t

array([[1],
       [2],
       [3]])

In [50]:
v_t_t = np.transpose(v_t) # transpoe of transpose returns the primary matrix
v_t_t

array([[1, 2, 3]])

In [54]:
v.T.T

array([[1, 2, 3]])

In [51]:
# for matrices: transposing changes rows and columns
m = np.array([[5,12,6], [-3, 0, 14]])
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [52]:
m_t = np.transpose(m)
m_t

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [55]:
# the beter way to transpose is .T
m.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

### Multiplication

In [64]:
# inner product or scaler product or dot product
x = np.array([2,8,-4])
y = np.array([1, -7,3])
np.dot(x,y)

-66

In [68]:
x = np.array([[2,8,-4]])
x

array([[ 2,  8, -4]])

In [69]:
x.T

array([[ 2],
       [ 8],
       [-4]])

In [71]:
np.dot(x, x.T)

array([[84]])

In [75]:
# scaler dot multiplied by a vector: multiplication by a scaler does not shange the shape and only changes the scale

In [76]:
y = np.array([1, 2,3])
np.dot(2,y)

array([2, 4, 6])

In [77]:
# or
2*y

array([2, 4, 6])

In [78]:
# dot product of matrices
m = np.array([[5,12,6], [-3, 0, 14]])
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [79]:
# scaler . matrix
2*m

array([[10, 24, 12],
       [-6,  0, 28]])

In [80]:
np.dot(m,2)

array([[10, 24, 12],
       [-6,  0, 28]])

In [82]:
# matrix.matrix  # the number of the columns of the first matrix must be equal to the number of the rows of the second matrix
m = np.array([[1,1,1], [-3, 0, 14]])  # 2*3
n = np.array([[1,2,3,4], [5, 0, 1,0],[1,1,1,1]]) # 3*4
np.dot(m,n)  # 2*4

array([[ 7,  3,  5,  5],
       [11,  8,  5,  2]])

In [1]:
import pandas as pd 

In [3]:
m = np.array([[12,0,1,3], [2, 3, 0, 7],[6, 1, 2, 0]])
m_df = pd.DataFrame(m)
m_df

0  1  2  3
0  12  0  1  3
1   2  3  0  7
2   6  1  2  0

In [4]:
m_df.loc[:,1:2]

1  2
0  0  1
1  3  0
2  1  2

In [5]:
m_df.loc[:, 1:2].max(axis=1)

0    1
1    3
2    2
dtype: int32